# Generated by Django 4.1.5 on 2023-01-23 19:46

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="image_url",
            field=models.ImageField(
                blank=True, null=True, upload_to=student.models.upload_to
            ),
        ),
    ]
