services:
  ssluzbauns1:
    image: dovvla/betterssluzbauns
    ports:
      - "8081:8080"
  ssluzbauns2:
    image: dovvla/betterssluzbauns
    ports:
      - "8082:8080"
  ssluzbapmf:
    image: dovvla/betterssluzbapmf:current
    environment:
      - SSLUZBA_UNS_URL=http://ssluzbauns
    volumes:
      -./media_pmf:/usr/src/app/ssluzba_pmf/mediafiles:ro
    ports:
      - "8001:8000"
  ssluzbaftn:
    image: dovvla/betterssluzbaftn:current
    environment:
      - SSLUZBA_UNS_URL=http://ssluzbauns
    volumes:
      -./media_ftn:/usr/src/app/ssluzba_ftn/mediafiles:ro
    ports:
      - "8002:8000"
  ssluzbapravni:
    image: dovvla/betterssluzbapravni:current
    environment:
      - SSLUZBA_UNS_URL=http://ssluzbauns
    volumes:
      -./media_pravni:/usr/src/app/ssluzba_pravni/mediafiles:ro
    ports:
      - "8003:8000"
  ssluzbauns:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - ssluzbauns1
      - ssluzbauns2
    ports:
      - "8080:80"
