services:
  ssluzbauns1:
    image: dovvla/betterssluzbauns
    ports:
      - "8081:8080"
  ssluzbauns2:
    image: dovvla/betterssluzbauns
    ports:
      - "8082:8080"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - ssluzbauns1
      - ssluzbauns2
    ports:
      - "8080:80"
