# Generated by Django 4.1.5 on 2023-01-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profesor",
            fields=[
                (
                    "jmbg",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("ime", models.CharField(max_length=100)),
                ("prezime", models.CharField(max_length=100)),
            ],
        ),
    ]
