name: ci

on:
  push:
    branches:
      - "master"

jobs:
  build-and-push-uns:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        env:
          IMAGE_TAG: ${{ github.sha }}
        with:
          context: ./ssluzba_uns/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/betterssluzbauns:current
  build-and-push-ftn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        env:
          IMAGE_TAG: ${{ github.sha }}
        with:
          context: ./ssluzba_ftn/ssluzba_ftn/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/betterssluzbaftn:current
  build-and-push-pmf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        env:
          IMAGE_TAG: ${{ github.sha }}
        with:
          context: ./ssluzba_pmf/ssluzba_pmf/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/betterssluzbapmf:current
  build-and-push-pravni:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        env:
          IMAGE_TAG: ${{ github.sha }}
        with:
          context: ./ssluzba_pravni/ssluzba_pravni/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/betterssluzbapravni:current
